### ISSUE TITLE
Task list not rendering ⚠️

### ISSUE THREAD

**Issue by oyeabhijit** [saswatsamal/markview#5]
## Expected output:
<p align="center">
  <img width="1000" src="https://user-images.githubusercontent.com/67273840/125388827-d7932180-e3bd-11eb-8d86-08eff63139ff.png" alt="Expected output">
</p>

## Current output:
<p align="center">
  <img width="1000" src="https://user-images.githubusercontent.com/67273840/125388643-7d925c00-e3bd-11eb-81a4-697e782325bd.png" alt="Current output">
</p>

**Comment by saswatsamal** [comment]
Yes, there are some rendering issues. Currently it is not able to render the tasks, tables..
I'll look into the documentation of showdown.js.
